// Can be generated by openapi spec
export type TDeployments = typeof import('././api/Deployments.json');
export type TEnvironments = typeof import('././api/Environments.json');
export type TProjects = typeof import('././api/Projects.json');
export type TReleases = typeof import('././api/Releases.json');

// Utils
export type ArrayElement<A> = A extends readonly (infer T)[] ? T : never;
